version: '3.8'

services:
  database:
    image: mongo
    ports:
      - "27017:27017"  # Map container's port 27017 to host's port 27017
    volumes:
      - mongo_data:/data/db  # Persist MongoDB data

  backend:
    image: abdullahtanveer/api:dailyback
    environment:
      - PORT=4000
    ports:
      - "4000:3001"  # Map container's port 3001 to host's port 3001
    depends_on:
      - database  # Wait for the database container to start before starting the backend
    environment:
      MONGO_URI: mongodb://database:27017/todo-list  # MongoDB connection URL

  frontend:
    image: abdullahtanveer/client:dailyfront
    environment:
      - PORT=4001
    ports:
      - "4001:3000"  # Map container's port 3000 to host's port 3000
    depends_on:
      - backend  # Wait for the backend to start before starting the frontend

volumes:
  mongo_data:  # Define a named volume for MongoDB data persistence
